[build]
  command = "npm install && npm run build && npx prisma migrate deploy && npx prisma generate"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200